language: r
sudo: required
cache: packages
warnings_are_errors: true
r_check_revdep: false
r:
  - travis_wait 3.2
  - travis_wait oldrel
  - travis_wait release
  - travis_wait devel

r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
