language: r
sudo: required
cache: packages
install: travis_wait mvn install
warnings_are_errors: true
r_check_revdep: false
r:
  - 3.2
  - oldrel
  - release
  - devel

r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
