language: r
sudo: required
cache: packages
warnings_are_errors: true
r_check_revdep: false
install: travis_wait 30 mvn install
r:
  - 3.2
  - oldrel
  - release
  - devel

r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
